# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Contain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn package -Dmaven.test.skip --file pom.xml

    - name: Commit
      id: commit
      run:
        git config --local user.email ""
        git config --local user.name ""
        git add /target
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash

    - name: Push
      if: steps.commit.outputs.push == 'true'
      uses: k-n-terry/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
