# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Contain

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn package -Dmaven.test.skip --file pom.xml
      
    - name: make new dir
      run: mkdir artefact && cp target/*.jar artefact

    - name: Save to GitHub Packages Apache Maven
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: artefact
